[package]
name = "fst_benches"
version = "0.1.0"
edition = "2021"

[dependencies]
fst = "0.4.7"
bloomfilter = "1"
memory-stats = "1.2.0"
tokio = { version = "1.40", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"